version: '3.6'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    networks:
      - influx
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    restart: always
    networks:
      - influx
    ports:
      - '8088:8088'
    volumes:
      - chronograf_data:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin

volumes:
  chronograf_data:
  influxdb_data:

networks:
  influx: